### PR TITLE
Upgrade to go 1.19, python 3.9 and install libffi-dev

### PR DESCRIPTION
**Pull request by jayakasadev**
# Description
The `python:3.8-slim` container is missing the `libffi` package which causes the installation of python's `cffi` to fail. As such, I added `libffi-dev` explicitly.
# Changes:
* Dockerfile
  * Upgrade to `go:1.19`
  * Upgrade to `python:3.9-slim`
  * Install `libffi-dev` in `python:3.9-slim`
* Update go deps

### CODE REVIEW

**Comment by colinhoglund** [comment]
Hey @jayakasadev, can you please add some detail regarding the purpose of this change. Specifically the addition of `libffi-dev`.

**Comment by jayakasadev** [comment]
@colinhoglund should I close this or remove the `libffi-dev` so we can use the latest go and python versions?

**Comment by colinhoglund** [comment]
> @colinhoglund should I close this or remove the `libffi-dev` so we can use the latest go and python versions?

Either works for me.

**Comment by colinhoglund** [comment]
Closing this for now, since it's not entirely necessary.

**Pull request closed without merging**
